### PR TITLE
fixed typo of example five selector

### LINKED ISSUE #1: Second example of advanced generic child ranges has wrong selector
First, thank you for your awesome examples. They are great and easy to follow.

But your second example of **advanced generic child ranges** has duplicate wrong selector from first example at lines here:
https://github.com/jamesmenera/mastering--nth-child/blob/master/index.html#L182-L185

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #1

### CODE REVIEW

**Comment by AndyOGo** [comment]
@jamesmenera 
@natevw 
May I ask you to review my PR.

**Comment by AndyOGo** [comment]
@natevw 
@jamesmenera 
Any change you look into this?

**Comment by natevw** [comment]
@AndyOGo Sorry, I don't think I'm an admin on this repo. Sounds like James isn't sure how useful the site is anymore: https://twitter.com/jamesmenera/status/894460169345679360

Personally I still occasionally reference it and would be a bit sad to see it go, but I don't know what else is out there.

[And hi @jamesmenera :-) Hope you are well and lemme know if you're ever up visiting!)

**Comment by jamesmenera** [comment]
@natevw @AndyOGo I am sorry, I forgot about this. I have merged it. Thanks for the pull request

**Comment by AndyOGo** [comment]
@natevw @jamesmenera 
Awesome. I'm happy to see this merged:)
I think the site is awesome and super simple, everyone should use it

**Pull request merged**
